---
- name: NTP 서버 설정 (master)
  hosts: master
  become: true
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
    - import_tasks: 03.setting_ntp/ntp_server.yml

- name: NTP 클라이언트 설정 (elastic)
  hosts: elastic
  become: true
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
    - import_tasks: 03.setting_ntp/ntp_client.yml
