---
- name: Ensure kibana base directory exists
  ansible.builtin.file:
    path: "{{ kibana_base_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user | default('wbl') }}"
    group: "{{ ansible_user | default('wbl') }}"

- name: Set kibana archive name
  ansible.builtin.set_fact:
    kibana_archive: "{{ (elk_packages_list | select('search', 'kibana') | list | first | default('')) | basename }}"

- name: Fail if kibana archive is not defined
  ansible.builtin.fail:
    msg: "No kibana package found in elk_packages_list."
  when: kibana_archive == ""

- name: Extract kibana package to base directory
  ansible.builtin.unarchive:
    src: "{{ elk_packages_dir }}/{{ kibana_archive }}"
    dest: "{{ kibana_base_dir }}"
    remote_src: true
    owner: "{{ ansible_user | default('wbl') }}"
    group: "{{ ansible_user | default('wbl') }}"
    extra_opts:
      - --strip-components=1

- name: Ensure kibana working/config/certs directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user | default('wbl') }}"
    group: "{{ ansible_user | default('wbl') }}"
  loop:
    - "{{ kibana_base_dir }}"
    - "{{ kibana_base_dir }}/config"
    - "{{ kibana_base_dir }}/config/certs"
