---
- name: base_packages 생성
  ansible.builtin.file:
    path: "{{ base_packages }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user | default('wbl') }}"
    group: "{{ ansible_user | default('wbl') }}"

- name: base_packages RPM 다운로드
  ansible.builtin.yum:
    name: "{{ packages }}"
    download_only: true
    download_dir: "{{ base_packages }}"
    state: present
  become: true

- name: base_packages 디렉토리 및 RPM 소유자 정렬
  ansible.builtin.file:
    path: "{{ base_packages }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user | default('wbl') }}"
    group: "{{ ansible_user | default('wbl') }}"
    recurse: true
