---
- name: NFS 클라이언트 롤백 (elastic)
  hosts: elastic
  become: true
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
    - name: NFS 마운트 해제 및 fstab 제거
      ansible.posix.mount:
        path: "{{ nfs_export_path }}"
        state: absent
    - name: 마운트 지점 디렉터리 삭제
      ansible.builtin.file:
        path: "{{ nfs_export_path }}"
        state: absent

- name: NFS 서버 롤백 (master)
  hosts: master
  become: true
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
    - name: /etc/exports에서 공유 설정 제거
      ansible.builtin.lineinfile:
        path: /etc/exports
        regex: "^{{ nfs_export_path | regex_escape }}\\s"
        state: absent
    - name: exportfs 반영
      ansible.builtin.command: exportfs -ra
      changed_when: false
    - name: 공유 디렉터리 삭제
      ansible.builtin.file:
        path: "{{ nfs_export_path }}"
        state: absent
