---
- name: chrony.conf 구성 (elastic)
  ansible.builtin.copy:
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      # Managed by Ansible - NTP client config
      server {{ ntp_local_host }} iburst

      sourcedir /run/chrony-dhcp
      driftfile /var/lib/chrony/drift
      makestep 1.0 3
      rtcsync

      keyfile /etc/chrony.keys
      ntsdumpdir /var/lib/chrony
      leapsectz right/UTC
      logdir /var/log/chrony

- name: chronyd 서비스 활성화 및 시작 (elastic)
  ansible.builtin.service:
    name: chronyd
    state: restarted
    enabled: true
